version: '3.8'

services:
  fastapi:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: fastapi_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_SERVER=redis_server
      - REDIS_PORT=6379
      - CACHE_TIME=3600
    depends_on:
      - redis
    command:
      sh -c "
      pip install -r requirements.txt &&
      uvicorn app:app --host 0.0.0.0 --port 8000
      "

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"
